### ISSUE TITLE
Random Forest accuracy is reduced severely with the addition of zero-information features

### ISSUE THREAD

**Issue by Zero3** [algorithmfoundry/Foundry#53]
Disclaimer: This could very well be a bug in my code. Perhaps someone could try to reproduce locally.

I've stumbled upon a weird problem. I'm using `RandomForestFactory` with the following parameters:
- ensembleSize: 200
- baggingFraction: 1.0
- dimensionsFraction: 0.2
- maxTreeDepth: Integer.MAX_VALUE
- minLeafSize: 1

Consider the following trivial dataset: 10 samples where 5 are labelled 'A' and 5 are labelled 'B'. There is just one feature, with the value '1' for 'A' samples and the value '0' for 'B' samples. As to be expected, I am able to achieve a 100% prediction accuracy on this dataset.

*However*, if I add 100 zero-information features to the dataset, something weird happens. If the samples are given random values of either '0' or '1' for these features, the accuracy falls to ~75%. If the samples are all given a value of just '0' instead, the accuracy falls further down to ~52% (i.e. only slightly better than random guessing).

I compared with Weka's Random Forest implementation with similar parameters, and get 100% accuracy in all 3 cases.

Any ideas?

**Comment by jbasilico** [comment]
Normally random forests grow out trees all the way and don't prune, and as such they are susceptible to losing performance with many random features due to overfitting. This is because each tree node only samples some number of the features to look at . In your case its 20%, so only 20% of nodes have a chance of seeing the good feature. It looks like Weka's implementation has an option to do pruning (they call it backfitting). Are you using that option?

**Comment by Zero3** [comment]
I see. I checked the source, and backfitting is disabled by default. I don't enable it anywhere.

**Comment by Zero3** [comment]
I came back to look further into this issue and now I cannot reproduce it. I fixed some bugs in my code in the meantime which I suspect was the cause of this issue. So I'll close this again. Apologies for the confusion!
